### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by anarchy9388** [TheMysteriousX/SNMPv3-Hash-Generator#1]
Traceback (most recent call last):
  File "/usr/bin/snmpv3-hashgen", line 6, in <module>
    from scripts.snmpv3_hashgen import main
  File "/usr/lib/python3.4/site-packages/scripts/snmpv3_hashgen.py", line 25
    return f"{user}/{hash(Kul_auth)}/{hash(Kul_priv)}/{mode}"
                                                            ^
SyntaxError: invalid syntax

**Comment by anarchy9388** [comment]
Ahh python 3.4 :(

**Comment by Yannis100** [comment]
With Python 3.6.8, I have the following error
```
Traceback (most recent call last):
  File "/usr/local/bin/snmpv3-hashgen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/scripts/snmpv3_hashgen.py", line 54, in main
    esxi = format_esxi(user, Kul_auth, Kul_priv, mode, hash)
  File "/usr/local/lib/python3.6/dist-packages/scripts/snmpv3_hashgen.py", line 25, in format_esxi
    return f"{user}/{hash(Kul_auth)}/{hash(Kul_priv)}/{mode}"
TypeError: 'staticmethod' object is not callable
```

Edit : The issue occurs only when specifying `--hash sha1/md5`
